send_anonymous_usage_stats: false
Hackathon:
    target: Snowflake_DB
    outputs:
        Snowflake_DB:
            type: snowflake
            account: JXGPFAR-REVOLT_PARTNER
            user: USER_01
            password: Dataistheanswer01!
            database: HACKATHON
            warehouse: HACKATHON_WH
            schema: TEAM_01